name: Deploy Docker

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        uses: ./.github/actions/unit-tests

  deploy:
    name: Build and push ingest + Airflow
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push images
        uses: ./.github/actions/deploy-docker
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
